version: '3.8'

services:
  backend:
    build: ./BE
    ports:
      - "3000:3000"
    volumes:
      - ./BE:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./FE
    ports:
      - "5173:5173"
    volumes:
      - ./FE:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
